### ISSUE TITLE
Confirm displayed data matches raw data wrt timezones

### ISSUE THREAD

**Issue by ajaypillarisetti** [vargovargo/SouthGatePA#1]
Do TZs displayed in browser match the raw data? Confirm.

**Comment by vargovargo** [comment]
the raw data (using sensor 29 as a test, first obs at 2018-04-13 03:31:59 UTC) uses UTC, and the timestamp in the table on the browser shows 3:30 am but I think it should be UTC - 8 or 7:30 Pm the previous day. I will look into it. 
:

**Comment by ajaypillarisetti** [comment]
Yeah, it is probably borked. Easy enough to fix -- the bigger headache is dygraphs, for which the timezone support is hot garbage. Has to be manually offset. All that said, it shouldn't be too bad to figure out the offsets for the table and graph and implement them. LMK what you find.

**Comment by vargovargo** [comment]
i noticed in the reactive chunks you already take away the 8x60x60...?

**Comment by vargovargo** [comment]
Could we just handle it up front by correcting the times right after the setnames(input_data)...
```input_data[, Timestamp := as.POSIXlt.date(Timestamp)-28800]```

**Comment by ajaypillarisetti** [comment]
I think we're all set now. Closed with commit 9b91dcd.
